version: '2'
services:
  maven:
    build:
      context: ./maven
      dockerfile: Dockerfile
    volumes:
      - ./maven:/boxfuse-sample-java-war-hello/target

  tomcat:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    links:
      - maven
    ports:
      - "8080:8080"
    volumes:
      - ./maven:/opt/tomcat/webapps
    volumes_from:
      - maven